### ISSUE TITLE
Default Style Persists in the Calendar

### ISSUE THREAD

**Issue by chiyeon** [waymondrang/CanvaStyle#1]
![image](https://user-images.githubusercontent.com/44148480/147371330-d5d281cf-95e3-4c7e-bccc-2887a27fa38f.png)

Entering the calendar mode on Canvas yields the above results. It appears the dark mode styling isn't being applied to these elements, even if it looks like the text color/font and such is.

From what I can tell, the calendars all have primary child `tbody` elements with the class `fc-body` for their content. In my testing, changing the `background-color` attribute of these elements changed the background properly, though in your own testing and application you may find different / more proper ways, given there is still a lot more styling to be done.

**Comment by waymondrang** [comment]
Thank you for taking the time to open an issue, explain the problem, and even offer a solution! I've added a patch to the extension that attempts to add dark mode coverage for the calendar page on Canvas.

![image](https://user-images.githubusercontent.com/57642450/147401080-03fddba2-38d8-4a90-9064-711bd57f4c85.png)

Please continue to use dm4c and report any inconsistencies or problems.

Thanks again and happy holidays!

**Comment by chiyeon** [comment]
Thank you for addressing my grievances. Your work is stellar. I will
continue to report any other issues I find.

Happy holidays!
