### ISSUE TITLE
Default Style Persists in Unpublished Courses

### ISSUE THREAD

**Issue by chiyeon** [waymondrang/CanvaStyle#5]
### Picture of Issue
![image](https://user-images.githubusercontent.com/44148480/147372035-20578558-7197-497f-ae86-1e266cd91be1.png)

### Steps to Replicate
**Prerequisites**
- Have a valid Canvas Account
- Be Enrolled in a Course that isn't Published

**Steps**
- Enter a valid Canvas session
- Click on _Courses_ in the main navigation panel
- Click on the _All Courses_ option in the Courses navigation

### Description
All `course-list-table-row` elements that represent a class not yet published default to the standard "light mode" background color, unless hovered. I believe this can be remedied by overwriting the default `background-color` style declaration of the `course-list-unpublished-course-row` class.

### Information
**Computer Specifications**
 - ASUS ROG Zephyrus G15 (GA503QR)
 - **Processor**: AMD Ryzen 9 5900HS with Radeon Graphics
 - **Ram**: 40.0 GB (39.4 GB usable)
 - 64-bit operating system, x64-based processor
 - **Pen and touch**: Pen support
 - **OS:** Windows 11 Home version 21H2
    - **Installed On:** 10/10/2021
    - **OS build**: 22000.376
 - Laptop is on top of a collapsible plastic table
 - The screen is angled about 105 degrees from closed

**Connected Devices**
I endeavored to include as much pertinent information as I could. Hopefully this is of use.
 - Stock ASUS ROG barrel charger
    - Charger is placed face up on a wooden floor
 - Anker USB-C Hub & connected Devices (Anker USB C Hub, Aluminum USB C Adapter with 4 USB 3.0 Ports, for MacBook Pro 2018/2017, ChromeBook, XPS, Galaxy S9/S8, and More)
    - Raleno 1080p Webcam, style: C30 (1080P Webcam, Desktop Camera with Dual Microphones, for PC/Mac Book/Laptop. Suitable for Windows, MacOS, NetWare, Linux) 
    - Nektar GX61 (Nektar, 61-Key Impact GX61 Controller Keyboard)
    - 2 Connected Keyboards Below
 - beyerdynamic SOUL BYRD (In-ear headset with balanced sound and good resolution)
 - Logitech PRO X SUPERLIGHT (Logitech PRO X SUPERLIGHT Wireless Gaming Mouse - mouse - LIGHTSPEED - white)

**Keyboard**
_Connected to the USB-C hub_
 - **Primrose Lilac prime_e**
    - **Case:** Primrose prime_e Stacked Acryllic Gasket Mount Case by Idyllic Keyboards
    - **Mount**: O-ring Burger Mount (Polypropylene plate)
    - **Switches**: POM Durocks
       - Lubed with 205g2105 7:3 mix
       - Previously filmed with Deskeys Gasket 3mm Switch Films, removed
       - POM housing
       - P3 (Proprietary UHMWPE blend) stem
       - 5 pin PCB mount
       - **Spring**: 63.5g SPRiT Complex Spring
    - **Stabilizers**: Two 2u Durock v2 Stabilizers (clear housings) 
       - Holee Modded with BAND-AID® Brand Flexible Fabric Bandages XL, 10 Count
    - **Keycaps**: EnjoyPBT Milky Purple Doubleshot ABS
 - **cu7**
    - Capsunlocked cu7 6-key macropad with rotary encoder
    - Aluminum CNC'd case
    - **Switches**
       - 2x JWK x qwertyqop Quartz linear 
          - Lubed with 205g2105 7:3 mix
          - **Top Housing**: Polycarbonate / Nylon blend
          - **Bottom Housing:** Special Polyamide Blend
          - P3 (Proprietary UHMWPE blend) stem
          - 5 pin PCB mount
          - **Spring:** 63.5 stock spring
       - 1x Kailh Box Navy
          - SMD compatible
          - IP56 waterproof/dustproof
          - Clicky 90g Peak Switch
       - 3x "Lilyos" (Sakurios/Lilac Linear Frankenswitch)
          - Lubed with 205g2+105 7:3 mix
          - **Top Housing**: Sakurios Housing
          - **Bottom Housing:** Sakurios Housing
          - **Stem:** POM Jwk Lilac Stem
          - **Spring:** Stock 62g Sakurios Stem

**Comment by waymondrang** [comment]
ok
